FROM maven:3.9.5-eclipse-temurin-17 AS build
WORKDIR /razorpay-demo

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /razorpay-demo

COPY --from=build /razorpay-demo/target/*.jar app.jar

EXPOSE 9092
ENTRYPOINT ["java", "-jar", "app.jar"]
