FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR ./razorpay-demo
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR ./razorpay-demo
COPY --from=build /app/target/*.jar app.jar
EXPOSE 9092
ENTRYPOINT ["java", "-jar", "app.jar"]

